<a href="https://colab.research.google.com/github/shabbar88/Exploratory_Data_Analysis/blob/main/Salary_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importing libraries and loading dataset
import numpy as np
import pandas as pd
data=pd.read_csv("https://raw.githubusercontent.com/shabbar88/LATEST-DATA--SCIENCE/refs/heads/main/Salaries.csv")

In [2]:
data

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

# 1.  Display Top 10 Rows of The Dataset

In [3]:
data.head(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.00,8601.00,189082.74,NaN,316285.74,316285.74,2011,NaN,San Francisco,NaN
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.90,134426.14,NaN,315981.05,315981.05,2011,NaN,San Francisco,NaN
7,8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256576.96,0.00,51322.50,NaN,307899.46,307899.46,2011,NaN,San Francisco,NaN
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011,NaN,San Francisco,NaN
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.00,0.00,17115.73,NaN,302377.73,302377.73,2011,NaN,San Francisco,NaN

# 2. Check Last 10 Rows of The Dataset

In [4]:
data.head(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.00,8601.00,189082.74,NaN,316285.74,316285.74,2011,NaN,San Francisco,NaN
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.90,134426.14,NaN,315981.05,315981.05,2011,NaN,San Francisco,NaN
7,8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256576.96,0.00,51322.50,NaN,307899.46,307899.46,2011,NaN,San Francisco,NaN
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011,NaN,San Francisco,NaN
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.00,0.00,17115.73,NaN,302377.73,302377.73,2011,NaN,San Francisco,NaN

In [5]:
data.tail(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148644,148645,Randy D Winn,"Stationary Eng, Sewage Plant",0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148645,148646,Carolyn A Wilson,Human Services Technician,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148646,148647,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148647,148648,Joann Anderson,Communications Dispatcher 2,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148648,148649,Leon Walker,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148649,148650,Roy I Tillery,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

# 3. Find Shape of Our Dataset (Number of Rows And Number of Columns)

In [6]:
data.shape

(148654, 13)

# 4.  Getting Information About Our Dataset Like Total Number Rows, Total Number of Columns, Datatypes of Each Column And  Memory Requirement

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

# 5. Check Null Values In The Dataset

In [8]:
data.isna().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                609
OvertimePay              4
OtherPay                 4
Benefits             36163
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              148654
dtype: int64

# 6. Drop ID, Notes, Agency, and Status Columns

In [9]:

data=data.drop(['Id','Notes','Agency','Status'],axis=1)

In [10]:
data

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011
...,...,...,...,...,...,...,...,...,...
148649,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014
148650,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014
148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014
148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014

# 7. Get Overall Statistics About The Dataframe

In [11]:
data.describe()

,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
count,148045.000000,148650.000000,148650.000000,112491.000000,148654.000000,148654.000000,148654.000000
mean,66325.448840,5066.059886,3648.767297,25007.893151,74768.321972,93692.554811,2012.522643
std,42764.635495,11454.380559,8056.601866,15402.215858,50517.005274,62793.533483,1.117538
min,-166.010000,-0.010000,-7058.590000,-33.890000,-618.130000,-618.130000,2011.000000
25%,33588.200000,0.000000,0.000000,11535.395000,36168.995000,44065.650000,2012.000000
50%,65007.450000,0.000000,811.270000,28628.620000,71426.610000,92404.090000,2013.000000
75%,94691.050000,4658.175000,4236.065000,35566.855000,105839.135000,132876.450000,2014.000000
max,319275.010000,245131.880000,400184.250000,96570.660000,567595.430000,567595.430000,2014.000000

# 8. Find Occurrence of The Top 5 Employee Names

In [12]:
data

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011
...,...,...,...,...,...,...,...,...,...
148649,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014
148650,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014
148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014
148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014

In [13]:
# Count occurrences of each employee name
name_counts = data['EmployeeName'].value_counts()
name_counts

EmployeeName
Kevin Lee                   13
Richard Lee                 11
Steven Lee                  11
William Wong                11
Stanley Lee                  9
                            ..
Jeffrey Skover               1
Ken Dever                    1
Kevin Whitfield              1
Granville McCollough III     1
Joe Lopez                    1
Name: count, Length: 110811, dtype: int64

In [14]:
name_counts.head(5)
#  we cam achieve top 5 using this approach as well

EmployeeName
Kevin Lee       13
Richard Lee     11
Steven Lee      11
William Wong    11
Stanley Lee      9
Name: count, dtype: int64

In [15]:
# Get the top 5 names
top_5_names = name_counts.nlargest(5)

print(top_5_names)

EmployeeName
Kevin Lee       13
Richard Lee     11
Steven Lee      11
William Wong    11
Stanley Lee      9
Name: count, dtype: int64

# 9. Find The Number of Unique Job Titles

In [16]:
uniq_job=data['JobTitle'].nunique()
print("Total number of unique Job Tile is {}".format(uniq_job))

Total number of unique Job Tile is 2159

# 10.Total Number of Job Titles Contain Captain

In [17]:
captain_count=len(data[data['JobTitle'].str.contains('CAPTAIN',case=False)])
print("Total Number of Job Titles Containing Captain is {}".format(captain_count))

Total Number of Job Titles Containing Captain is 552

# 11. Display All the Employee Names From Fire Department

In [18]:
fire_data=data[data['JobTitle'].str.contains('Fire',case=False)]['EmployeeName']
fire_data

4            PATRICK GARDNER
6                  ALSON LEE
8             MICHAEL MORRIS
9         JOANNE HAYES-WHITE
10             ARTHUR KENNEY
                 ...
145956      Kenneth C Farris
147556         Edward A Dunn
148021        Kari A Johnson
148209          Sheryl K Lee
148554       Lawrence F Gatt
Name: EmployeeName, Length: 5879, dtype: object

In [19]:
list1=[x for x in fire_data]

In [20]:
print("List of Employees in Fire Dept are: {}".format(list1))

List of Employees in Fire Dept are: ['PATRICK GARDNER', 'ALSON LEE', 'MICHAEL MORRIS', 'JOANNE HAYES-WHITE', 'ARTHUR KENNEY', 'DAVID FRANKLIN', 'MARTY ROSS', 'GEORGE GARCIA', 'VICTOR WYRSCH', 'JOSEPH DRISCOLL', 'JOHN HANLEY', 'RAYMOND GUZMAN', 'MONICA FIELDS', 'JOSE VELO', 'BRENDAN WARD', 'MICHAEL THOMPSON', 'THOMAS ABBOTT', 'THOMAS SIRAGUSA', 'MICHAEL THOMPSON', 'BRYAN RUBENSTEIN', 'KEN YEE', 'KIRK RICHARDSON', 'MICHAEL ROLOVICH', 'DARRYL HUNTER', 'KENNETH SMITH', 'CHARLES CRANE', 'ROBERT POSTEL', 'EDWARD ROLAND', 'RICHARD BUSALACCHI', 'KEVIN BURKE', 'BERT REYES', 'MICHAEL DELANE', 'EDUARDO GONZALEZ', 'ROBERT WINSLOW', 'LORRIE KALOS', 'JONATHAN BAXTER', 'MICHAEL BRYANT', 'MARY TSE', 'MARK GONZALES', 'PETE FAY JR', 'REX HALE', 'KEVIN SMITH', 'GREGORY STANGLAND', 'KEVIN TAYLOR', 'ERIKA HOO', 'LAUIFI SEUMAALA', 'PATRIC STEELE', 'MICHAEL WALSH', 'SAMSON LAI', 'SCOTT SCHOLZEN', 'KHAIRUL ALI', 'MICHAEL CASTAGNOLA', 'SEAN BONETTI', 'JOHN HICKEY', 'GLEN KOJIMOTO', 'EDWARD CHU', 'SOFIA MATHEWS', 'EDMUND DEA', 'ZACHARY PUMPHREY', 'MARK CASTAGNOLA', 'LUIS IBARRA-RIVERA', 'DONNIE HORNBUCKLE', 'TIM AREJA', 'RASMI CHAN', 'MICHAEL KEARNEY', 'MATTHEW MCNAUGHTON', 'KARL JURGENSON', 'OSCAR CABRERA', 'MARTIEN VERHAEG', 'CARL JEPSEN', 'GEORGE LYSENKO', 'HARRY PINKARD', 'ALBERTO PEDRUCO', 'DWAYNE CURRY', 'LEON WHITE', 'NATHAN HARDY', 'DENNIS SUTTER', 'DONALD FIELDS', 'SAMUEL ROMERO', 'OLLIE BANKS', 'THOMAS HARVEY', 'MARTIN BELTRAN', 'ROBERT TAI', 'CHRISTOPHER HAZEN', 'PIERRE FRANCOIS', 'TROY JOLLIFF', 'MICHAEL AHERN', 'ROBERT SERRANO', 'JAMES VANNUCCHI', 'PHILIP STEVENS', 'TIMOTHY SULLIVAN', 'CANTREZ TRIPLETT', 'NOEL MORONEY', 'GERALD MANSUR JR', 'ALAN HARVEY', 'WILLIAM RADER', 'GREGORY MCFARLAND', 'CLEMENTINO AVILA II', 'RYAN KENNEDY', 'JOHN ROCCO', 'ARNOLD CHOY', 'MIKE BREILING', 'ANDREW LOGAN', 'GLENN KIRCHER', 'TYRONE PRUITT', 'BROOK MANCINELLI', 'CHAD LAW', 'FERNANDO DEALBA', 'ROBERT STYLES', 'EDMUND VAIL', 'ANDREW SAITZ', 'ARNIE LEE', 'MITCHELL LEE', 'NEREE DASTOUS', 'MELISSA LERMA', 'RAYMOND CHAVEZ', 'FREDERICK BINKLEY', 'GUY GOODWIN', 'BERGLIOTH MATHEWS', 'PABLO SIGUENZA', 'BRIAN MURPHY', 'STEVEN WILLIAMS', 'MORGAN PETITI', 'PAUL URQUIAGA', 'JOHNSON YOU', 'DANIEL YONTS', 'DAVID THOMPSON', 'JAMES BLAKE', 'CLYDE CHRISTOBAL', 'THOMAS MURPHY', 'GLENN ORTIZ-SCHULDT', 'FERDINAND MENESES', 'ALVIN LAU', 'RYAN CREAN', 'SAMUEL NIETO', 'RUDY CASTELLANOS', 'MICHAEL GONZALES', 'JEFF IWASAKI', 'JENNIFER DEBERRY', 'ALEC BALMY', 'ROBERT LOPEZ', 'GREGORY CACHARELIS', 'RONALD PRUYN', 'JOHN KOSTA', 'RICKY HUI', 'ERNEST JOHNSON', 'TERENCE OSULLIVAN', 'KEVIN KUHN', 'MICHAEL MOYNIHAN', 'JOHN MURPHY', 'JOSEPH CUFF', 'MICHAEL SMITH', 'DANIEL ARMENTA', 'KENNETH CORDERO', 'ROBERT COLEMAN', 'NICOLETTE DIVECCHIO', 'JIM HALL III', 'THOMAS BUSBY', 'DUSTIN NOVO', 'DAVID HAWKINS', 'MAMI SUZUKI-VIDALON', 'JALAL AINEB', 'DANIEL MOLLOY', 'VINCENT PAMPANIN', 'MARK JOHNSON', 'BRENDAN MCGORRIN', 'ATTICA BOWDEN', 'DALE CARNES', 'VINCENT DAVIS', 'WILLIAM MCFARLAND', 'SAHIR PUTRUS', 'DENISE BAILEY', 'ANNETTE HOBRUCKER-PFEIFER', 'CHUTEH KOTAKE', 'RAEMONA WILLIAMS', 'JEFFREY BARDEN', 'MATTHEW CANNON', 'ROBERT GALLOT', 'RICHARD UNTALAN', 'VERNONICA JONES', 'ANTHONY ROBINSON', 'MANUEL PEGUEROS', 'THOMAS REY', 'RICHARD CURRIE', 'DEREK WING', "DENNIS O'NEILL", 'RUDOLPH ERLER', 'GAVIN ESTUPINIAN', 'JEFF COLUMBINI', 'ANDRE WILLIAMS', 'FLOYD ROLLINS', 'THOMAS KOHMANN', 'HENRY LARKIN', 'RAUL FRANCISCO', 'NICOL JURATOVAC', 'DAVID ZWYER', 'ALAN REYNAUD', 'PATRICK MULLANEY', 'DENISE NEWMAN', 'DAVID OWEN', 'JOHN FLORES', 'MICHAEL BELLO', 'MAGALY SAADE', 'JACK CHOW', 'JOHN CREMEN', 'JULIO ESCOBAR', 'FRANK KOSTA', 'DERIO DITO', 'ROBERT MUHAMMAD', 'FRANK HSIEH', 'EDWARD CAMPBELL', 'LENETTE THOMPSON', 'JOHN STANFIELD', 'MATTHEW HUTCHINSON', 'LOURDES RUSSELL', 'DWIGHT NEWTON', 'DAVID BROWN', 'VINCENT NOLAN', 'ABDUL KHADIR', 'TERENCE WOO', 'RAYCARDO AVILES', 'CHERISH MURDOCK', 'LARS ASPELIN', 'RICHARD GERING', 'ROBERT LA EACE', 'MARY KUCEL', 'VITANI BENJAMIN', 'JORGE PLATA', 'RAMON SIMON', 'ANESTO ESTRELLA', 'JANET BROCK', 'THOMAS FOGLE', 'KENNETH HUPKE', 'ROHAN KNIGHT', 'PATRICK GRIMESEY', 'DONALD PEOPLES', 'JOHN DARMANIN', 'EDWARD MOY', 'PAUL JUG', 'RONALD JOHANSEN', 'ROMELIA SCOTT', 'STEVEN MILLER', 'GREGORY ZANDERS', 'MILTON YUEN', 'AARON FISHER', 'STEPHEN MAGUIRE', 'VINCENT WONG', 'RONALD LEWIN', 'JESSE BAUTISTA', 'JAMES HUDSON', 'CARL DRAKE III', 'SARA COE', 'JOSEPH SCHIEBOLD', 'EDWARD BARBERO', 'CHRISTINE EMMONS', 'CHRISTOPHER PRATT', 'JAMES KIRCHER', 'DONALD GOGGIN', 'ANTHONY BENDIK', 'NORMAN CABA', 'KENNETH COFFLIN', 'LORENZO IBARRA', 'DANIEL MARTINO', 'ERICK MARTINEZ', 'WILLIAM STORTI', 'JONATHAN OKAMURA', 'GREGORY PERATA', 'SEAN MCKINNEY', 'DOUGLAS CALDERON', 'GAVIN MCGOLDRICK', 'EDDY WOO', 'ERNEST CARRILLO', 'BROOK BAKER', 'JOEL DELIZONNA', 'ROBERT REED', 'TODD PLUNKETT', 'ANTHONY WEST', 'MATTHEW SCHWARTZ', 'ALEXANDER DOUGLAS JR', 'CHARLES HARDIMAN', 'ARNOLD WOO', 'BRUCE FINE', 'MEIR GORDON', 'ANTENOR MOLLOY', 'MARC PEARSON', 'MANUEL ALVARENGA', 'JOHN CHRISTY', 'WILLIAM LAU', 'DUSTIN WINN', 'FERNANDO JUAREZ', 'GERALD HESS', 'GERALD GAUER', 'DAVID MORRIS', 'JEFFREY AMDAHL', 'FRANCO CALZOLAI', 'DAVID MONTEVERDI', 'CLAUDIA VALENTINO', 'JAMES LOWE', 'GLENN FREY', 'ERIC LEAL', 'MICHAEL RUBIN', 'KEITH ONISHI', 'TODD PRAKIN', 'MICHAEL MULLIN', 'SPENCER NAKAO', 'THERESE GEE', 'GLEN ZORRILLA', 'MICHELE GRINDSTAFF', 'ROBERT WONG', 'DENNIS SULLIVAN', 'PATRICK RABBITT', 'SCOTT SANDINE', 'LARRY JACOBS', 'MICHAEL KIRK', 'JOSEPH BARBERO', 'JERRY CHIANG', 'JAMES PERRY II', 'MICHAEL COLEMAN', 'DANIEL ROMERO', 'MOISA TELLEZ', 'JAMES AYACHE', 'ERIC MONTALVO', 'STANLEY PERRIATT', 'ANNE TAM', 'ETHAN BANFORD', 'CHRISTIAN COLLIER', 'TIMOTHY NEFF', 'JOHN SIKORA', 'ELLEN STEIN', 'VICTOR GONZALES', 'DEAN WHITTAKER', 'MICHAEL PATT', 'JAMES KIMBALL', 'CHRISTOPHER MADSEN', 'MATTHEW ALBA', 'KAEO NACUA', 'JEANINE NICHOLSON', 'EDWARD LONDONO', 'ART RUIZ', 'JAMES DRAPER', 'GABRIEL SHIN', 'TERRY SMERDEL', 'MATTHEW LANE', 'DOUGLAS SPIKES', 'WILLIAM WYCKOFF', 'CHARLES MC COY', 'MICHAEL HASTEY', 'KENNETH LOMBARDI', 'DAMEN TOLLIVER', 'YUSUFU CAUNGULA', 'CHRISTOPHER DUGAN', 'LEONARD CAULDER', 'RANDALL HIRO', 'PAUL GALLEGOS', 'CONRAD BENITEZ', 'PAUL SHIMAZAKI', 'RAUL SANDOVAL', 'LLOYD GOLDBERG', 'MICHAEL HORTA', 'TRACY FRANTZ', 'STEPHEN GIACALONE', 'TERENCE WHITE', 'MARK MACIAS', 'ELYSE DUCKETT', 'AISHA KRIEGER', 'BERNARD LANTIN', 'NICHOLAS BAZARINI', 'BRIDGET CULLINANE', 'JAMES QUIRKE', 'GEORGE PETTY', 'WILLIAM WONG', 'ANTHONY MARTINEZ', 'JAY CLELAND', 'DESMOND COTTER', 'CHASE WILSON', 'MICHAEL JONES', 'TYSON YEE', 'STEVEN WOMBACHER', 'JAMES OCONNELL', 'ALLEN WONG', 'VICTOR WONG', 'STEPHEN CRUZ', 'STEVEN BOKURA', 'RICHARD STEVENS', 'SCOTT EBERHART', 'DANIEL BRIGHT', 'BRIAN WALSH', 'DAVID NONOMURA', 'MARK HAYES', 'JOSEPH GIACOMINI', 'JASON BLAND', 'MICHAEL KIRTLEY', 'JEAN PINTO', "PAUL O'KANE", 'CHRISTOPHER POSEY', 'STEPHEN FINNEGAN', 'SOLA CHUOP', 'PAUL MCDONAGH', 'DAVID SPENCER', 'JOSHUA PEREIRA', 'MICHAEL CASTAIN', 'ROGER PHILLIPS', 'FRANK CERCOS IV', 'ERIK BROWN', 'JOSHUA CUSICK', 'DANIEL DECOSSIO', 'KEVIN OSULLIVAN', 'K CARLTON BISCEVIC', 'DANIEL TAUBER', 'JASON HARRELL', 'EILEEN MCCRYSTLE', 'ALLEN WONG', 'JANEEN PIROSKO', 'KELLY HOLT', 'JOSEPH HALLISY', 'ERIC STIVESON', 'WARREN HOUSE', 'MICHAEL LAWSON', 'SHELIA HUNTER', 'PHILIP TELESFORO', 'SHAYNE KAIALOA', 'EDWARD YUP', 'ANITA PARATLEY', 'BARRY LO', 'ROBERT ARZAVE', 'NASH QUINTO', 'DEAN CRISPEN', 'RAFAEL GORDON', 'RUBEN MONTERO', 'BRANDON TOM', 'JOEL SOTO', 'DAVID MURRAY', 'NIKKI GRIFFEY', 'JAMES ONOE', 'PAUL SAITZ', 'MICHAEL TEUPEL', 'KAREN HEALD', 'DANIEL FLEMING', 'EDWARD LABRADO', 'MARIA NILSSON', 'RICHARD MCGEE', 'DARRYL LOO', 'JONATHAN HUGGINS', 'JOHN YEE', 'MICHAEL SIMON', 'RONALD LAU', 'RAMON BARRETO JR', 'CLAUDIO RIVIECCIO', 'SUSAN DEMARTINI', 'GERALD SCULLION', 'JENNIFER MATHEWS', 'KEVIN CHOCKER', 'LISA MOY', 'JAMES FEWELL', 'JOSEPH SALLADY', 'KATHLEEN HAROLD', 'JULIE DEJARLAIS', 'DARIUS LUTTROPP', 'EDWARD BANKS', 'NEAL CAVELLINI', 'SHON BUFORD', 'JOHN MURNANE', 'DENISE PEMBERTON', 'MICHAEL MAGALONG', 'JOHN WON', 'THERESA FOGARTY', 'CARL BARNES', 'DANIEL BECKWITH', 'JEFFREY COVITZ', 'RICHARD WENDLAND', 'SIULAGI SALA', 'BERNARD MAGUIRE', 'JIRO YAMAMOTO', 'MELCHOR PICARDAL', 'STEPHEN CASSIDY', 'JONATHAN LOW', 'DAVID SAITZ', 'CHRIS SALAS', 'VALERIE STEPHENSON-BOYD', 'SCOTT DARMSTADT', 'ADRIENNE SIMS', 'DAVID LESTER', 'JEREMY SILVA', 'JOEL SATO', 'CARLOS HOY', 'KYLE MERKINS', 'LORGE QUANT', 'JAMES KOTTER', 'TINA SEIBERT', 'JOHN CABA', 'DOUGLAS MANGUIAT', 'MICHAEL FERRARA', 'JON DEL BINO', 'JEFFREY WONG', 'RAYMOND LEE', 'GAVIN MARCONI', 'DAVID RUSSELL', 'DOMINIC OTTOBONI', 'NEAL JAYMES', 'REGINA MORLEY', 'TOD STEPHENSON', 'GEORGE SMITH', 'ANGELA ROMERO', 'JOSEPH BEAM', 'ALEXANDER UNTALAN', 'JOE LUI', 'CHRISTOPHER HEUERMAN', 'JOHN GRANT', 'STEPHEN GONZALES', 'DAVID RITTER', 'WALTER VILLAVICENCIO', 'LEONARDO HARRIS', 'EDWARD AMIT', 'MICHAEL DIETZEN', 'KEITH PHILLIPS', 'MAURICE CASTAIN', 'KEVIN PARDINI', 'BRUCE MARTIN', 'MARC KASPER', 'JAY LEE', 'AL GARZA', 'DANIEL CASEY', 'JOE CHAN', 'KATHLEEN GILBRAITH', 'MICHAEL COCHRANE', 'JOHN HERNANDEZ', 'MIKAEL BAYLESS', 'BRUCE SAMSON', 'CRISTEO REYES', 'DAVID CRESPIN', 'REUBEN RAMOS', 'JASON REICHARD', 'RICHARD NOLAN', 'RICK FIGARI', 'RUDY GUAJARDO', 'KATHRYN CARDINALE', 'JARED KUNKEL', 'MICHAEL MALONEY', 'RICHARD ESPINOZA', 'KEVIN WALSH', 'DAVID SMILEY', 'MARCO NOCON', 'JULIO DELUCCHI', 'THOMAS JOHANNESSEN', 'GREG WYRSCH', 'HENDRYCK LASAK', 'WAYMAN DUNCAN', 'ETHAN JACKSON', 'CRAIG JOHNSON', 'STEVE SILVESTRICH', 'CLIFTON HONG', 'LAURA KELLY', 'TAMI TURNER', 'MARIBETH JENSEN', 'DEREK OLEARY', 'DAISY YU', 'JAMES MAC DONELL', 'KJELL HARSHMAN', 'THOMAS MCGUIRE', 'ERIK ZAMMARCHI', 'SHAWN ZIMMERMAN', 'ANDREW SOBOZINSKY', 'MICHAEL MENEFEE', 'MICHAEL JUAN', 'CAROLINE PRIEM', 'RICHARD LOPES', 'NATASHA PARKS', 'BRUCE GUITRON', 'GIDEON PRICE', 'MICHAEL CHARLTON', 'KEITH ALMIROL', 'LUKE MICHAELIS', "PATRICK D'ARCY", 'LAWRENCE CONRAD', 'MICHAEL PETERSON', 'GEOFFREY QUESADA', 'ROBERT VIGIL', 'BRUNO WALTHER', 'MARK NICHOLAS', 'GILLIAN SMITH', 'ROBERT DOTSON III', 'KENDRICK LOW', 'MICHAEL MURPHY', 'GABRIEL LOPEZ', 'BRIAN BURNS', 'GREGORY COLLACO', 'KENNETH MARTIN', 'KENNETH DUNN', 'MICHAEL BARRY', 'STEPHEN CASSIDY', 'LAWRENCE POWELL', 'JANICE HAYES', 'MICHAEL CAMPANALI', 'ROBERT KISHI', 'DENNIS FOSTER', 'CHARLES FARRUGIA', 'FREDERICK REPPUN', 'RONALD ROBINSON', 'GERALD WHITE', 'FRANK ROLDAN', 'ALBERT BRONSON JR', 'MICHAEL DAY', 'TIMOTHY FARMER', 'BRICE PEOPLES', 'AMY SWANSON', 'DAWN DEWITT', 'JERRY SHEAR', 'NICHOLAS HOLL', 'GREGORY STEWART', 'HEATHER PIPER', 'DANIEL MCCLOSKEY', 'MARC EVANS', 'RANDALL HENDERSON', 'RONALD CUPIDO', 'ALAN CAMARILLO', 'PAUL CRAWFORD', 'STEPHEN ENGLER', 'AARON STEVENSON', 'ROBERT SCHEPPLER', 'EUGENE ADAMS', 'CATHERINE EMMONS-SAMSON', 'CONRAD BROSAS', 'BRENT STUCKERT', "DAVID D'AMICO", 'KENNETH JONES', 'KIMBERLY GRINTON', 'MICHAEL VIEIRA', 'CYNTHIA LUCERO', 'TODD WEDDLE', 'HEIDI BERGMARK', 'EDWARD MARTINEZ', 'GEORGE CERNA', 'MEGAN FRANZEN', 'HANSJUERG ENZ', 'MICHAEL DUNCAN', 'YOON LEE', 'BRIAN COLLINS', 'JEFFERY CHIN', 'JUSTIN APOSTOLI', 'MATTHEW LEE', 'STEVE FIGUEROA', 'JOSEPH VIGLIZZO', 'CHRISTOPHER BONN', 'GIL INTENGAN', 'ANTHONY RIVERA', 'SCOTT DOONAN', 'CYNTHIA FAENZI', 'ANSON WU', 'MARTA MCGOVERN', 'JOSEPH DEVATY', 'MICHAEL GUAJARDO', 'CHARLES KWONG', 'PAUL MANGIOLA', 'RONALD PEREZ', 'LAVERNE MALIGA', 'DARRYL BREWSTER', 'JUSTIN SCHORR', 'BRIAN MCCARTHY', 'GREG TRUMPLER', 'KENNETH MCCARTHY', 'KINNIE JAMERSON JR', 'ERIC BOTELHO', 'HARRY HIGGINS', 'JOSHUA WILSON', 'HERMAN WOO', 'WILLIAM DAVIS', 'THERESA WOLOWIC', 'DONYALE HOYE', 'PETER GROSS', 'JOSE ZALBA', 'JAMES REIDY', 'GARRETH MILLER', 'MICHELLE MCCOY', 'THERESA KWAN', 'CHUCK WATANABE', 'ANTHONY SMERDEL', 'GARRET LUCIER', 'JASON WATROUS', 'RACHEL MARCIC', 'TIMOTHY MCHALE', 'RICKY YEE', 'ERICA ARTESEROS', 'GENERAL JAMES JR', 'MATTHEW TARLACH', 'PETER LEE', 'JAMES CARLIN', 'JOSEPH SILVA', 'THOMAS THORNTON', 'ANTON SHELTON', 'WILLIAM DORSEY', 'MARK SIKORA', 'DAWN ROSALES', 'EDWARD GHILARDI JR', 'ROBERT TURNQUIST', 'DARRELL STONE', 'MICHAEL CREEDON', 'DOMINIC SHANLEY', 'SEAN MULLANE', 'DANIEL DOUGLASS', 'WAYNE WONG', 'DONALD BARRICK', 'MICHAEL FUCCIOLO', 'RICHARD FAUST', 'ALLEN BOGDANOFF', 'CHRISTOPHER YOCK', 'ALVIN SELVA', 'KATHY AUSTIN', 'BROCK WELLS', 'ADAM BUSTILLOS', 'KIMBERLY MC KEON', 'NICHOLAS PAYNE', 'PATRICK BRYAN', 'EIGIL QWIST', 'JOHN SHANLEY', 'KENNETH DEVER', 'DAVID PLANKA', 'NATHAN SZUTU', 'DAVID SWEENEY', 'ANTHONY BRANCHCOMB', 'JOHN K CHOY', 'SALLY SAXTON', 'EMMON LEW', 'AMY ENG', 'WILFREDO VARONA', 'JAMES MELLBERG', 'PAUL MCHUGH', 'RAMON SERRANO', 'THOMAS KIERNAN', 'TERRY FITZSIMMONS', 'MARTIN SPALKA', 'GREGORY BLATMAN', 'IAN DERAMMELAERE', 'LYLE WOODSON', 'THOMAS OCONNOR', 'STEVEN METZ', 'JASON SIMMONS', 'RALPH BLANCHARD', 'MARC DEVILLE', 'JULIE MAU', 'PATRICK SULLIVAN', 'TIMOTHY TIERNAN', 'HEIDI BOHLER BARNETT', "DAMON O'BRIEN", 'SEAN JOHNSTON', 'KEVIN MC KEON', 'DONNY BENDO', 'THOMAS OERTLI', 'CHRISTOPHER BENZ', 'PERRY CHOY', 'JOHN DILUZIO', 'KEVIN NIELSEN', 'JUSTIN BROWN', 'REY BUZON', 'WILLIAM CHIN', 'PETER ARNAUTOFF', 'RICHARD COTTON', 'CYNTHIA RICKERT', 'CHADWICK ERTOLA', 'CECILIA JIANG', 'KAAN CHIN', 'NANCY BARSOTTI', 'MARY MINOGUE', 'JOE NALDO', 'LARRY PARA', 'THEODORE CARTER', 'MARCIEL RIVERA', 'ALLEN WU', 'SHANE MURPHY', 'JOHN CHUNG', 'PHILIP LEE', 'MANUEL LOPES', 'IVAN GOMEZ', 'TOMIE KATO', 'DARREN BORTMAS', 'CHESTER SPIRLIN', 'KERBY LAU', 'JOHN LOPES', 'WILLIAM JACKSON', 'MICHAEL PARKER', 'JOHN DRAKE', 'STEPHEN MARCOTTE', 'EUGENE EDEN-JR', 'ROBERT NEUNEKER', 'CRAIG LOUIE', 'KIMBERLY HATCHER', 'JASON WOO', 'DANIEL GRIFFIN', 'GREGORY SIMPSON', "TRACY O'KEEFFE", 'MARY CARDER', 'ANDREW BIRKHOFF', 'PHILIP BENSON', 'SHERMAN TILLMAN', 'SHIRLEY SZELA', 'KAREN KERR', 'JOHN DUNN', 'ROBERT MELLO', 'PATRICIA LEE', 'MICHIE WONG', 'REXIE MEGIA', 'PATRICK MORAN', 'REBECCA ATWATER', 'JEREMIAH RIBEIRO', 'THOMAS HANEY', 'THORIN SHATTUCK', 'STEPHEN MC PARTLAN', 'JOHN CURD', 'WILLIAM BOYLE', 'ROBERT MCDONALD', 'VICTOR HURTADO', 'NATALIE LEVCHENKO', 'WILLIAM LINNEY', 'JANETTE NEVES RIVERA', 'STANLEY LEE', 'RYAN TOBY', 'BRYAN HENDON', 'MICHAEL ORLANDO', 'WILLIAM POWELL', 'JAMES APP', 'SCOTT HUA', 'ROBERT ZLATUNICH', 'THOMAS BOLLINGER', 'FREDERICK PUTT', 'MICHAEL MARKS', 'JEFF RUSTEEN', 'CHARLES DALEY', 'SHANE FRANCISCO', 'ROGER NG', 'SAMUEL HO', 'ALAN WONG', 'BRETT LYNCH', 'OCTAVIO-JAME LEONARDO', 'TIMOTHY KELLY', 'PATRICK HIGGINS', 'SEAN VISSER', 'NATHAN SHAPIRO', 'MARK KANE', 'RICHARD SLATTERY', 'ROBYN GRALICER', 'HUCKLEBERRY RAMSAY', 'TIMOTHY WONG', 'GREGORY JONES', 'RAMON CHEA', 'KRISTA SMITH', 'JASON CHAN', 'ANDREW THOMAS', 'JOHN LEMBERG', 'LEONARDO CAVESTANY', 'LAWRENCE YUP', 'CLIFTON MERRILL', 'KENNETH LINNEY', 'JACK TAYLOR', 'CHRISTOPHER CANDIA', 'DANIELLE SORRENTI', 'JEFFREY BABB', 'KIMBERLY HIROSHIMA', 'SCOTT KINKADE', 'JASON CORTEZ', 'ANTHONY GARIBALDI', 'MICHAEL SONG', 'KENG YAN CHAN', 'MARIO ROMERO', 'HEATHER BUREN', 'BRITTON SMITH', 'RICHARD BROWN', 'ROBERT MILLER', 'BRENT MARKS', 'MICHAEL HOELSKEN', 'DANIEL GRACIA', 'JOHN WILKOSZ', 'ELMEN WU', 'WILLA ORTEGA', 'ROBERT JONES II', 'JOEL NEWTON', 'MARK HARDEMAN', 'BARRY WONG', 'EMIL CUAN', 'JAMES KUCHARSZKY', 'BRIAN BALLARD', 'ANNIE HODDINOTT', 'STEVE MULLER', 'TIMOTHY HOWE', 'CHRISTOPHER SPEAR', 'JOHN FOGARTY', 'WILLIAM YEUNG', 'JAMES UNTALAN', 'DAT TRUONG', 'MATTHEW SCOLA', 'MATTHEW ADAMS', 'JAMES MULHOLLAND', 'MARIFI ESTEVES', 'BRENDAN CORMACK', 'MARY BOUCHER', 'HENRY SCOBLE JR', 'DWAYNE NEWTON', 'YVETTE ORTEGA', 'CAROL WYLEY', 'GEORGE KOUREMETIS JR', 'ANTHONY YEE', 'RICHARD MCCOO', 'MICHAEL QUINN', 'COREY YEH', 'NORMAN WONG', 'MARIANO ELIAS JR', 'ALISON YEE', 'LANCE MARTIN', 'LEONEL TINGIN', 'GARY ALTENBERG', 'MICHAEL MARTINEZ', 'RAYMOND POYDESSUS', 'PAUL ORLANDO', 'EILEEN NEEDHAM', 'THOMAS MANNION', 'SABINE BALDEN', 'RONALD VANPOOL', 'MICKI JONES', 'CAROL CONLEY-BODIN', 'PEDRO MARTINEZ', 'DANIEL LUI', 'LAIN SALSTRAND', 'PRIVADO GUMABAY', 'JOSEPH HORTON', 'KETTY FEDIGAN', 'ERIN MURPHY', 'ARAM MARAVILLAS', 'RUSSELL ZIMMERMAN', 'JOHN MANNING', 'CHARLES MCGOWAN-FACIANI', 'NICHOLAS YUEN', 'JOHN SILVA JR', 'CRISTINA KOSTA', 'AMADOR HERRERA', 'JANICE HOAGLIN', 'KEVIN SHEA', 'ROBERT RAMIREZ', 'LESLIE WONG', 'ANDREW GLEASON', 'HENRY TAM', 'ZACHARY TIBBITS', 'MICHAEL RUSTIA', 'FRANCES FOCHA', 'EDWIN DIAZ', 'PAUL DAIJO', 'WAYLEN WANG', 'NICHOLAS HELMER', 'ELIZABETH LEAHY', 'PATRICK HANNAN', 'JAMES FERRANTE', 'GILBERT JACOBS JR', 'PATRICK DOHERTY', 'HUMBERTO PILARTE', "THOMAS O'BRIEN", 'ALBERT HOM', "TILAFAIGA TA'APE JR", 'RICHARD MILES', 'OSBALDO GUTIERREZ', 'TRACY CAVARETTA', 'HELEN KIEFFER', 'DONNA SPIRLIN', 'SAGIV WEISS-ISHAI', 'GREGORY BROWNE', 'JAMES PARISH', 'JOHN TUIASOSOPO', 'KEN AINSWORTH', 'JOHNATHAN ASHBROOK', 'LEONOR SALDANA', 'IRENE YBARRA', 'NORMAN YUP', 'SEAN MATSUBAYASHI', 'NEIL HOPPER', 'RUSSELL ROBY', 'WARREN DER', 'ANTONIO VERNON', 'PATRICIA FLOOD', 'ROBERT CAPPA', 'JOHN DANNER III', 'DAMIAN GARCIA', 'STEPHEN KLOSTER', 'KEVIN TOM', 'KIRT THOMASON', 'TRACE MCCULLOCH', 'DAVID DAWLEY', 'GEORGE KARAWANNY', 'STEVEN WONG', 'JOHN KOSITZIN', 'SHANNON STABILE', 'KATHERINE ALBA-SWANSON', 'BENJAMIN FRANKS', 'MARK OHARA', 'JOHN MCNULTY', 'GAYLORD GABRIEL', 'BRIAN KYONO', 'CARY BUTCHER', 'CHRIS RAY-ROHAN', 'WAYNE CHEW', 'JON SARGENT', 'TIMOTHY FINCH', 'RACHAEL ATCHISON', 'ALAN DE BELLA', 'LORI CLETHEN', 'FRANK BONAL', 'KRISTINA NELSON', 'DIANE VAN DER HEIDEN', 'BRIAN BARDEN', 'SETH RUBENSTEIN', 'MELINDA TALMADGE', 'FRANCIS SPERISEN III', 'KATHLEEN MCELHENEY', 'DAVID DUNG', 'MATTHEW EGAN', 'GUILLERMO CASILLAS', 'SUEON WONG', 'STEVEN STRONG', 'PAUL LEE', 'MYRON SCOTT', 'JOSEPH CERTAIN', 'MICHAEL CLARK', 'DAVID CHAVEZ', 'PEDRO GONZALEZ JR', 'ROBERT BOUGHN', 'JAMES BEEM', 'JOEL ZERMENO', 'ELI CHAN', 'MICHAEL AGUILAR', 'MEGAN OCONNELL', 'JOSHUA DICKER', 'JARED FRANKLIN', 'AGUSTIN LARUE', 'KEVIN KRAMER', 'PATRICIA LUI', 'RICHARD BRITTON', 'GUADALUPE MARIN', 'LESTER LESAVOY', 'DENNY ACOSTA', 'CLYDE WATARAI', 'MATTHEW WAYNE', 'GEARY HORIKIRI', 'DAMIAN ORDUNA', 'BETTRIETTA KIME', 'R SCHNELKER', 'JON CORBETT', 'ROBERT COLLINSON', 'JENNIFER WARDEN', 'DANIEL MARTINEZ', 'ERIC KWAN', 'MIKE WONG', 'EDWIN RAMOS', 'HARRISON KONG', 'MARK GRADNEY', 'SASHA GRANDE', 'RAYMOND NG', 'DAVID WATERS', 'JAMES GREEN', 'ROBBIN HEWITT', 'WILLIAM MADSEN', 'JASON MISHLER', 'KERRY MANN', 'KEITH BARAKA', 'KEVIN SALAS', 'SIG WALLEN', 'JENNIFER STOW', 'ANDRE BROWN', 'JOHN HARRINGTON', 'DAVID AMITUANAI', 'MICHAEL TIN', 'VICTOR LUBET', 'RONALD CADITAN', 'JUAN LA CHICA', 'WILLIAM REILLY', 'PATRICK MARTINEZ', 'MARIO FLAVIANI', 'PAUL MC DERMOTT', 'LARRY DEEN', 'DUSTIN RUFF', 'DENNIS YU', 'ROBERT MATEIK', 'KAILIN WATERMAN', 'JAMES LEONARD', 'MIMI WOO', 'APRIL BASSETT', 'FRANCISCO OCHOA', 'ROGER FONG', 'STEPHANIE MCKNIGHT', 'PEDRO VIEIRA', 'GREGORY LOUIE', 'JENNIFER MARTINEZ', 'JOSHUA SMITH', 'KEVIN KELLY', 'TONY LEW', 'JOSHUA HOYT', 'ANTONIO LUIS ROCHA', 'RICHARD ARCHIBALD', 'GREGORY SAVIN', 'PAUL BARRY', 'LAWRENCE RUSTIA', 'THEODORA REILLY', 'COLIN MACKENZIE', 'DENNIS KELLY', 'ROBERT RECENDEZ', 'JOHN CHEUNG', 'DEAN LUNDIE', 'KAISER LAM', 'LAWANDA ANDERSON', 'PATRICK MURPHY', 'DEE LAU', 'DAVID YI', 'PETER WALKER', 'MORGAN LEE', 'DEWAYNE ECKERDT', 'NORMAN KWAN', 'FRANCINE BRISTOW', 'ADAM WOOD', 'MARILYN CHAVEZ', 'STEVEN SELCK', 'FREDERICK STUMPP', 'JOHN ROGERS', 'MARK ZHANG', 'PETER LI', 'ERIC STOREY', 'DONALD PRICE JR', 'WILLIAM BIGARANI', 'BENJAMIN CANEDO', 'ERIC SOTO', 'DUANE RIVERA', 'JOHNNY WILLIAMS', 'CHRISTINE WILLIAMS', 'CHRISTIAN JEFFREY', 'DOMINIC BORDACHAR', 'ELI THOMAS', 'AUDRY LEE', "ROSS O'REILLY", 'JOHN MAGUIRE', 'LARRY ABELLA', 'LAWRENCE JEW', 'EDGAR COVARRUBIAS', 'MARILYN LUM', 'MANUEL DACALANIO', 'ERIC TANIMURA', 'RENO BLANCHFIELD', 'JOSHUA PARKS', 'JONATHAN RIDER', 'NICHOLAS BRADY', 'KARL JURADO', 'DAVID AYMERICH', 'ERIC HIPP', 'MICHAEL CARION', 'REYNER MEDINA', 'MICHAEL SANDERS', 'HENRY TASTO', 'RAMON FLORES', 'K P KASHIMA', 'ERIC LOUIE', 'GREGORY YOUNG', 'SCOTT HELLESTO', 'BRIAN JESSON', 'DANIEL DUNNIGAN', 'CARLA MURPHY', 'MICHAEL SHANLEY', 'ANTHONY DIRICCO', 'RICHARD HOM', 'DAVID PAGAN', 'SEAN PASTORI

In [21]:
len(list1)

5879

# 12. Find Minimum, Maximum, and Average BasePay

In [22]:
data['BasePay'].max()

319275.01

In [23]:
data['BasePay'].min()

-166.01

In [24]:
data['BasePay'].mean()

66325.4488404877

# 13. Replace 'Not Provided' in EmployeeName' Column to NaN

In [25]:
# Replace 'Not Provided' with NaN
data['EmployeeName'] = data['EmployeeName'].replace('Not Provided', np.nan)

In [26]:
data

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011
...,...,...,...,...,...,...,...,...,...
148649,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014
148650,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014
148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014
148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014

# 14. Drop The Rows Having 4 Missing Values

In [27]:
len(data.columns)

9

In [28]:
# data.dropna(thresh=len(data.columns) - 1)

In [29]:

# rows having 5 missing values
data[data.isnull().sum(axis=1)==4]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
148646,Not provided,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014
148650,Not provided,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014
148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014
148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014

In [30]:
data.drop(data[data.isnull().sum(axis=1)==4].index,axis=0,inplace=True)

In [31]:
data

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011
...,...,...,...,...,...,...,...,...,...
148645,Carolyn A Wilson,Human Services Technician,0.00,0.00,0.00,0.0,0.00,0.00,2014
148647,Joann Anderson,Communications Dispatcher 2,0.00,0.00,0.00,0.0,0.00,0.00,2014
148648,Leon Walker,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014
148649,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014

# 15. Find Job Title of ALBERT PARDINI

In [32]:
name=data[data['EmployeeName']=='ALBERT PARDINI']['JobTitle']
name1 = [x for x in name]

In [33]:
print("Job Tiitle of ALBERT PARIDINI is {}".format(name1))

Job Tiitle of ALBERT PARIDINI is ['CAPTAIN III (POLICE DEPARTMENT)']

# 16. How Much ALBERT PARDINI Make (Include Benefits)?

In [34]:
data

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011
...,...,...,...,...,...,...,...,...,...
148645,Carolyn A Wilson,Human Services Technician,0.00,0.00,0.00,0.0,0.00,0.00,2014
148647,Joann Anderson,Communications Dispatcher 2,0.00,0.00,0.00,0.0,0.00,0.00,2014
148648,Leon Walker,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014
148649,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014

# 16. How Much ALBERT PARDINI Make (Include Benefits)?

In [35]:
my_data=data[data['EmployeeName']=='ALBERT PARDINI']['TotalPayBenefits']

In [36]:
type(my_data)

pandas.core.series.Series

In [37]:
my_data.values

array([335279.91])

In [38]:
print("ALBERT PARDINI make {}".format(my_data.values))

ALBERT PARDINI make [335279.91]

# 17.Display Name of The Person Having The Highest BasePay

In [39]:
data[data['EmployeeName']==data['BasePay'].max()]

Empty DataFrame
Columns: [EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year]
Index: []

In [40]:
highest_basepay_name = data.loc[data['BasePay'].idxmax(), 'EmployeeName']

print("The person with the highest BasePay is: {}".format(highest_basepay_name))

The person with the highest BasePay is: Gregory P Suhr

# 18.Find Average BasePay of All Employee Per Year

In [41]:
average_basepay_per_year = data.groupby('Year')['BasePay'].mean().reset_index()

print(average_basepay_per_year)

   Year       BasePay
0  2011  63595.956517
1  2012  65436.406857
2  2013  69630.030216
3  2014  66564.421924

# 19. Find Average BasePay of All Employee Per JobTitle

In [42]:
average_basepay_per_jobtitle = data.groupby('JobTitle')['BasePay'].mean().reset_index()

print(average_basepay_per_jobtitle)

                                            JobTitle       BasePay
0                                      ACCOUNT CLERK  43300.806506
1                                         ACCOUNTANT  46643.172000
2                                  ACCOUNTANT INTERN  28732.663958
3                        ACPO,JuvP, Juv Prob (SFERS)  62290.780000
4                                      ACUPUNCTURIST  66374.400000
...                                              ...           ...
2153                           X-RAY LABORATORY AIDE  47664.773077
2154                           X-Ray Laboratory Aide  46086.387100
2155  YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS  52609.910000
2156                              Youth Comm Advisor  39077.957500
2157                                     ZOO CURATOR  43148.000000

[2158 rows x 2 columns]

# 20. Find Average BasePay of Employee Having Job Title ACCOUNTANT

In [43]:
# Filter for employees with the job title ACCOUNTANT
accountants = data[data['JobTitle'] == 'ACCOUNTANT']

# Calculate the average BasePay
average_basepay_accountant = accountants['BasePay'].mean()

print(f"The average BasePay of employees with the job title ACCOUNTANT is: {average_basepay_accountant}")

The average BasePay of employees with the job title ACCOUNTANT is: 46643.172

# 21. Find Top 5 Most Common Jobs

In [44]:
top_jobs = data['JobTitle'].value_counts().head(5)

print(top_jobs)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [46]:
data

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011
...,...,...,...,...,...,...,...,...,...
148645,Carolyn A Wilson,Human Services Technician,0.00,0.00,0.00,0.0,0.00,0.00,2014
148647,Joann Anderson,Communications Dispatcher 2,0.00,0.00,0.00,0.0,0.00,0.00,2014
148648,Leon Walker,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014
148649,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014